import * as React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { }
import {
  AppType,
  DocumentContext,
  DocumentInitialProps,
  DocumentProps,
} from 'next/dist/shared/lib/utils';
import { EmotionCache } from '@emotion/cache';

import emotionAndTssCache from  '../shared/stylesCache';
import { theme } from '../shared/themes';

export default class CustomNextDocument extends Document {
  static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps | DocumentProps> {
    const origRenderPage = ctx?.renderPage;
    const { emotionCache, tssCache } = emotionAndTssCache();
    const { extractCriticalToChunks } = createEmotionServer(emotionCache);
    const initialProps = await Document.getInitialProps(ctx);

    /* eslint-disable prettier/prettier */
    try {
      ctx.renderPage = () =>
        origRenderPage({
          enhanceApp:
            // eslint-disable-next-line react/display-name


              (
                App:
                  | AppType
                  | React.ComponentType<{ muiCache: EmotionCache; tssCache: EmotionCache }>
              ) =>
              (props) =>
                (
                  <App
                    muiCache={muiCache}
                    tssCache={tssCache}
                    {...props}
                  />
                ),
        });

      console.info(muiCache, tssCache);

      const muiStyles = extractCriticalToChunks(initialProps.html);
      const muiStyleTags = muiStyles.styles.map((style) => (
        <style
          key={style.key}
          data-emotion={`${style.key} ${style.ids.join(' ')}`}
          dangerouslySetInnerHTML={{ __html: style.css }}
        />
      ));

      console.table(muiStyles);

      return {
        ...initialProps,
        styles: [...React.Children.toArray(initialProps.styles), ...muiStyleTags],
      };
    } catch (err: unknown) {
      console.error({ error: err || 'caught an error' });
      return {
        ...initialProps,
        // error: err ? err : 'Error rendering custom styles...'
      };
    } finally {
      console.info(
        initialProps?.html?.valueOf(),
        initialProps?.head?.valueOf(),
        initialProps?.styles?.valueOf()
      );
    }
    /* eslint-enable prettier/prettier */
  }

  render() {
    return (
      <Html lang="en">
        <Head>
          <meta
            name="theme"
            content={theme.palette?.mode}
          />
          <meta
            name="description"
            content="Generated by create next app"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
function createEmotionServer(emotionCache: EmotionCache): { extractCriticalToChunks: any; } {
  throw new Error('Function not implemented.');
}

